RELEASE_TYPE: patch

This patch fixes an internal error when running in an :pypi:`IPython` repl or
:pypi:`Jupyter` notebook on Windows (:issue:`2319`), and an internal error on
Python 3.5.1 (:issue:`2318`).
